### ISSUE TITLE
Few errors/corrections

### ISSUE THREAD

**Issue by drnickyoung** [passatgt/gdpr-cookie-notice#1]
Hi,

An excellent bit of code. Few minor issues:

The example in the readme

`  marketing: [SSID'] //Cookies in the marketing category.`

You are missing a ' in there. Should be

`  marketing: ['SSID'] //Cookies in the marketing category.`

You also need to note the script needs the init at the bottom of the page, before closing body tag.

**Comment by passatgt** [comment]
Thanks, updated
