### ISSUE TITLE
Settings Modal Not Opening

### ISSUE THREAD

**Issue by stripitdown** [passatgt/gdpr-cookie-notice#2]
This looks like a great cookie consent solution for GDPR compliance; exactly what I hoped I'd find.

I've run into a problem, however. 

I've followed the instructions as far as implementing the gdprCookiesEnabled event, but the modal box isn't opening when I click on 'Cookie Settings' – nor if I click a button I've added to my Cookies policy. I can't seem to find out why this might be. Can anyone help?

[Happy to provide further info if needed]

**Comment by passatgt** [comment]
Hi, just fixed it.
