### ISSUE TITLE
Option to change cookie settings?

### ISSUE THREAD

**Issue by brasileric** [passatgt/gdpr-cookie-notice#3]
Hi,
In the demo when you click Accept all cookies, the bar disappears but then there is no option anymore to change the settings when you change your mind. An change option is required by the GDPR law as far as I know.

**Comment by passatgt** [comment]
Just add the class "gdpr-cookie-notice-settings-button" to a link or button and that will open the settings modal. This is described on the demo page btw.

**Comment by A1Click** [comment]
> Just add the class "gdpr-cookie-notice-settings-button" to a link or button and that will open the settings modal. This is described on the demo page btw.

Please, help me...When I add the class "gdpr-cookie-notice-settings-button", don't run and reopen the same page.
Why?
Thanks for your help and good job.
